[project]
name = "card-profiler"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
authors = [
    { name = "Mohamed", email = "mohamedsehrane314@gmail.com" }
]
requires-python = ">=3.14"
dependencies = []

[project.scripts]
card-profiler = "card_profiler:main"

[build-system]
requires = ["uv_build>=0.12.15,<0.13.0"]
build-backend = "uv_build"
